import Head from "next/head";
import Announcement from "./Announcement";
import Navbar from "./Navbar";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Rest In Cheese</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Announcement />
      <Navbar />
      {children}
    </div>
  );
};

export default Layout;
